import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


export default function Home() {

  return (
    <>
      <Head>
        <title>Header Menu Series</title>
        <meta name="description" content="Header Menu Series. Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keyword" content="header menu, 헤더메뉴, html 메뉴, css 메뉴"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={{pathname: "Type1/Type1" , query: {title: "Type1"}}}>Type1 가기</Link>
      </main>
    </>
  )
}
